USERNAME='username'
TIMEOUT='timeout'
IS_LOGGED_IN='isLoggedIn'
LAST_LOGIN_TIME='lastLoginTime'
LAST_LOGOUT_TIME='lastLogoutTime'
CONNECTION='connectionsocket'
BLOCKED_CLIENTS='blockedclients'
UNREAD_MESSAGES='unreadmessages'